import json
import re
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session
from backend.app.repositories.stylist_repository import StylistRepository
from backend.app.repositories.catalog_repository import CatalogRepository
from backend.app.repositories.profile_repository import ProfileRepository
from backend.app.repositories.wardrobe_repository import WardrobeRepository
from backend.app.providers.orchestrator import get_orchestrator
from backend.app.services.styling_engine import StylingEngine
from backend.app.services.query_translation import (
    contains_arabic,
    translate_query,
    translate_reply_to_arabic,
)
from backend.app.services.styling.outfit_prose import attach_prose, split_outfit_prose
from backend.app.services.styling.garment_gender import (
    gender_from_query,
    is_compatible as is_gender_compatible,
)
from backend.app.services.recommendation_constraints import constraints_from_payload, apply_constraints
from backend.app.services.styling.color_harmony import ColorHarmonyEngine
from backend.app.services.stylist_image_intake import (
    ParsedImage,
    PaletteColor,
    color_family_for_rgb,
    extract_palette,
    merge_palettes,
)
from backend.app.services.stylist_vision import VisionAnalysis, analyze_images
from backend.app.services.content_safety_service import (
    POLICY_VERSION as SAFETY_POLICY_VERSION,
    content_safety_service,
    refusal_for,
)


class StylistService:
    def __init__(self, db: Session):
        self.db = db
        self.stylist_repo = StylistRepository(db)
        self.catalog_repo = CatalogRepository(db)
        self.profile_repo = ProfileRepository(db)
        self.wardrobe_repo = WardrobeRepository(db)
        # Shared process-wide orchestrator so provider quarantine (cooldown)
        # state actually persists across requests.
        self.orchestrator = get_orchestrator()

    async def interact_with_stylist(
        self,
        user_id: Optional[int],
        prompt: str,
        session_id: Optional[int] = None,
        occasion: Optional[str] = None,
        budget_limit: Optional[float] = None,
        voice_input_used: bool = False,
        recommendation_constraints: Optional[Dict[str, Any]] = None,
        images: Optional[List[ParsedImage]] = None,
        include_wardrobe_items: bool = True,
        history: Optional[List[Dict[str, str]]] = None,
    ) -> Dict[str, Any]:
        images = list(images or [])
        # 0. Decode the images BEFORE anything is written. An unreadable picture
        #    is refused with nothing persisted. The bytes are used for analysis
        #    and then dropped: neither the message row nor the intent JSON ever
        #    carries them (FR-008).
        pixel_palettes = [extract_palette(img) for img in images]

        # 1. Retrieve or create session (supports guest user_id=None)
        session = self.stylist_repo.get_or_create_session(user_id, session_id)

        # 2. Add user message
        user_msg = self.stylist_repo.add_message(
            session_id=session.id,
            sender="user",
            content=prompt
        )

        # 2b. Moderation gate on the user's turn.
        #
        # Placed AFTER the user message is persisted and BEFORE any provider is
        # called, so a blocked turn still leaves an honest transcript (the
        # question was asked; CONFIT declined) and burns no provider quota.
        #
        # FAILS OPEN, unlike the wardrobe upload gate: if the classifier cannot
        # be reached the shopper still gets styling help from the deterministic
        # engine. Refusing to answer would be a worse outcome than a missing
        # moderation pass on text, and the asymmetry is stated in
        # docs/safety/confit_safety_policy_v1.0.0.md ("Calibration notes").
        if content_safety_service.configured:
            verdict = await content_safety_service.check_text(
                prompt, context="stylist_chat"
            )
            if verdict.should_block:
                refusal_text = refusal_for(verdict)
                assistant_msg = self.stylist_repo.add_message(
                    session_id=session.id,
                    sender="assistant",
                    content=refusal_text,
                    intent_json={"safety_blocked": True},
                    recommendations_json=[],
                )
                # The copy is authored by CONFIT policy, not generated by a
                # model. Attributing it to a model would repeat the exact defect
                # test_ai_model_truthfulness.py exists to prevent.
                return {
                    "id": assistant_msg.id,
                    "session_id": session.id,
                    "sender": "assistant",
                    "content": refusal_text,
                    "audio_url": None,
                    "intent_detected": {"safety_blocked": True},
                    "engine": f"CONFIT Safety Policy v{SAFETY_POLICY_VERSION}",
                    "recommendations": [],
                    "created_at": assistant_msg.created_at,
                }

        # 3. Retrieve user profile if authenticated
        usp = self.profile_repo.get_by_user_id(user_id) if user_id else None
        # Whether a PERSISTED profile actually provided the styles. The fallback
        # list below is a matching input, not a fact about the shopper — the
        # prose used to say "tailored to your Smart Casual profile" to an
        # anonymous caller because that distinction did not exist (measured
        # 2026-09-24; see services/styling/attribution.py).
        profile_styles_present = bool(usp and usp.style_archetypes)
        user_styles = json.loads(usp.style_archetypes) if profile_styles_present else ["Smart Casual", "Quiet Luxury"]
        user_colors = json.loads(usp.preferred_colors) if usp and usp.preferred_colors else ["Navy", "Beige", "Black"]
        # Only a user-stated budget (explicit request param, or text the parser
        # extracts) is a HARD constraint. A stored profile default is a soft
        # preference, so it must NOT mark the budget as explicit.
        explicit_budget = budget_limit if budget_limit is not None else None
        max_budget = budget_limit or (usp.budget_per_outfit_max if usp else 450.0)

        # 3b. Arabic -> English BEFORE intent parsing.
        #
        # StylingEngine._OCCASION_KEYWORDS is an English-only vocabulary, so
        # an Arabic request matched nothing, intent fell back to
        # style_source="default" and the shopper was asked to rephrase.
        # Measured on production: the Arabic form of a query returned 0
        # recommendations where its English equivalent returned 2. CONFIT
        # prices in EGP/AED/SAR with a fully Arabic UI, so that was its
        # primary market getting no recommendation at all.
        #
        # English input is returned untouched — no call, no latency. The
        # translated text is used for RETRIEVAL only; `prompt` keeps the
        # shopper's own words for the transcript and the reply.
        translation = await translate_query(prompt)
        search_prompt = translation.text

        # 4. Parse user intent, occasion, style, and slot expectations
        intent = StylingEngine.parse_intent(
            prompt=search_prompt,
            occasion_hint=occasion,
            budget_hint=explicit_budget,
            user_styles=user_styles,
            user_colors=user_colors,
            profile_styles_present=profile_styles_present,
        )
        # Ensure the composer always has a numeric ceiling for scoring even when
        # no explicit budget was stated (soft profile default).
        intent.setdefault("detected_budget", max_budget)
        if not intent.get("detected_budget"):
            intent["detected_budget"] = max_budget

        # 5. Graceful handling of ambiguous / low-signal requests (BRD 21,
        #    E2E-12): ask a clarifying question instead of returning confident
        #    fabricated outfits for gibberish or empty input.
        if intent.get("is_ambiguous") and not images:
            clarify_text = (
                "I want to style you well, but I didn't catch a specific occasion, "
                "style, or budget in that. Could you tell me a bit more — for example "
                "'a smart casual work outfit under $500' or 'a formal wedding look'? "
                "You can also tap an occasion: Work, Wedding, Party, or Casual."
            )
            assistant_msg = self.stylist_repo.add_message(
                session_id=session.id,
                sender="assistant",
                content=clarify_text,
                intent_json=intent,
                recommendations_json=[]
            )
            # No provider was called on this path (the prompt was too vague to
            # act on), so there is no engine to attribute. `engine: "none"` is
            # stated rather than left absent, so a client cannot mistake a
            # clarifying question for a generated styling answer.
            return {
                "id": assistant_msg.id,
                "session_id": session.id,
                "sender": "assistant",
                "content": assistant_msg.content,
                "audio_url": None,
                "intent_detected": intent,
                "engine": "none",
                "recommendations": [],
                "created_at": assistant_msg.created_at
            }

        # 5b. Mode A: analyse the shopper's images (vision chain, honest fallback).
        #     Mode is decided by what actually ran, not by what was requested. If
        #     vision is unavailable the turn is answered as Mode B and the reason
        #     is shown to the shopper.
        mode_requested = "A" if images else "B"
        mode_used = "B"
        fallback_reason: Optional[str] = None
        image_analysis: Optional[Dict[str, Any]] = None
        palette_items: List[Dict[str, Any]] = []
        vision: Optional[VisionAnalysis] = None
        if images:
            vision = await analyze_images(images, prompt)
            if vision.available:
                mode_used = "A"
                colour_check, palette_items = _cross_check_colours(pixel_palettes, vision)
                image_analysis = {
                    **vision.to_public(),
                    "colours": [
                        {"hex": c.hex, "family": c.family, "share": c.share}
                        for c in merge_palettes(pixel_palettes)
                    ],
                    "colour_check": colour_check,
                    "images": len(images),
                }
            else:
                fallback_reason = vision.reason
                image_analysis = {"available": False, "reason": vision.reason, "images": len(images)}
        intent["mode_requested"] = mode_requested
        intent["mode_used"] = mode_used
        if fallback_reason:
            intent["fallback_reason"] = fallback_reason

        # 6. Retrieve candidate products from the real catalog. Availability
        #    gate (BRD 15): only products with at least one in-stock SKU are
        #    eligible for recommendation; out-of-stock items are never composed.
        # Gender filter. The catalogue gained a `gender` column in migration
        # 0027 because it had none: a men's request returned women's heeled
        # sandals, since the composer had nothing to filter on.
        #
        # Read from the ORIGINAL prompt, not the translation — the Arabic
        # term is recognised directly, and a paraphrase can drop it.
        requested_gender = gender_from_query(prompt) or gender_from_query(search_prompt)

        all_products = [
            p for p in self.catalog_repo.filter_products(limit=100)
            if is_gender_compatible(getattr(p, "gender", None), requested_gender)
            if getattr(p, "skus", None) and any(s.is_in_stock and s.stock_level > 0 for s in p.skus)
        ]

        # 6b. Structured recommendation constraints. Palette is authoritative
        #     when it maps to catalog colour fields; fit is authoritative only
        #     where a concrete size from the request/profile can be checked
        #     against SKU stock. No AI and no fake confidence scores.
        constraint_meta = None
        if recommendation_constraints or usp:
            constraints = constraints_from_payload(recommendation_constraints, usp)
            all_products, constraint_meta = apply_constraints(all_products, constraints)
            intent["recommendation_constraints"] = constraint_meta

        # 7. Compose strict slot-based complete outfits grounded in the catalog
        recommended_outfits, alternatives_meta = StylingEngine.compose_outfits_with_meta(
            available_products=all_products,
            intent=intent,
            user_profile=usp,
            max_outfits=2
        )
        # Whether a second look was requested, published, or suppressed because it
        # held the same products as the first — part of the record, not a log
        # detail (styling/diversity.py explains the rule).
        if alternatives_meta.get("suppressed"):
            intent["alternatives"] = alternatives_meta

        # 6c. Mode A colour coordination. The image's extracted palette is scored
        #     against each composed look with the same ColorHarmonyEngine used
        #     everywhere else, and the looks are ordered by that score. A missing
        #     or uncertain palette changes nothing: the order then stays as composed.
        if mode_used == "A" and palette_items:
            for outfit in recommended_outfits:
                outfit["color_coordination"] = _coordinate_with_palette(outfit, palette_items)
            recommended_outfits.sort(
                key=lambda o: (o.get("color_coordination") or {}).get("score", -1),
                reverse=True,
            )
            intent["image_colour_coordination"] = [
                {"outfit_id": o.get("id"), **(o.get("color_coordination") or {})}
                for o in recommended_outfits
            ]

        # 6d. Wardrobe grounding (STY-03). Only a signed-in shopper has a wardrobe,
        #     and the response records whether it was actually consulted.
        wardrobe_meta: Dict[str, Any] = {"requested": bool(include_wardrobe_items), "used": False, "reason": None}
        owned_pieces: List[Any] = []
        if include_wardrobe_items:
            if not user_id:
                wardrobe_meta["reason"] = "Sign in to pair this look with the pieces you already own."
            else:
                owned_pieces = self.wardrobe_repo.get_user_items(user_id)
                if owned_pieces:
                    wardrobe_meta["used"] = True
                    wardrobe_meta["owned_items_considered"] = len(owned_pieces)
                else:
                    wardrobe_meta["reason"] = "Your wardrobe has no items yet."
        wardrobe_context_lines: List[str] = []
        if owned_pieces:
            for outfit in recommended_outfits:
                pairings = _wardrobe_pairings(outfit, owned_pieces)
                outfit["wardrobe_pairings"] = pairings
                wardrobe_meta["pairings"] = wardrobe_meta.get("pairings", 0) + len(pairings)
            primary_pairings = (recommended_outfits[0].get("wardrobe_pairings") if recommended_outfits else None) or []
            for pairing in primary_pairings:
                wardrobe_context_lines.append(
                    f"- The shopper already owns {pairing['title']} ({pairing['color_name']} {pairing['category']}); "
                    f"it pairs with the look's {', '.join(pairing['pairs_with'])}."
                )
        intent["wardrobe"] = wardrobe_meta

        primary_outfit = recommended_outfits[0] if recommended_outfits else None

        # Facts handed to the model as verified context (never as open invitations
        # to invent). Image analysis and wardrobe pieces are both checked facts.
        extra_context_parts: List[str] = []
        # Facts the model must respect, stated by the service (not inferred by the
        # model): how many looks were asked for against how many are shown, and
        # whether the shopper's own wardrobe was actually used.
        requested_looks = _requested_look_count(prompt)
        if requested_looks and requested_looks != len(recommended_outfits):
            extra_context_parts.append(
                f"The shopper asked for {requested_looks} looks; this reply shows "
                f"{len(recommended_outfits)}. Say so, and do not claim the others are shown."
            )
        if include_wardrobe_items and not wardrobe_meta.get("used"):
            extra_context_parts.append(
                "The shopper's own wardrobe was NOT used for this reply"
                + (f" ({wardrobe_meta['reason']})." if wardrobe_meta.get("reason") else ".")
            )
        if _mentions_own_items(prompt):
            extra_context_parts.append(
                "The shopper describes pieces they own in their message. Those pieces are "
                "not in CONFIT's records: do not present them as catalogue items, and do "
                "not say the look was built from them unless they are listed under owned pieces."
            )
        if mode_used == "A" and vision and vision.summary:
            extra_context_parts.append(f"Image analysis: {vision.summary}")
        if mode_used == "A" and image_analysis and image_analysis.get("colours"):
            colours = ", ".join(c["family"] for c in image_analysis["colours"][:4])
            extra_context_parts.append(f"Dominant colours in the shopper's photo(s): {colours}.")
        if wardrobe_context_lines:
            extra_context_parts.append("Owned pieces that pair with the primary look:\n" + "\n".join(wardrobe_context_lines))
        extra_context = "\n".join(extra_context_parts) or None

        # Earlier turns: text only, oldest first, bounded. Client-supplied, so
        # they are context for the model and are never trusted as facts.
        conversation = [
            {"role": str(t.get("role", "user")), "content": str(t.get("content", ""))[:1200]}
            for t in (history or [])[-STYLIST_HISTORY_MAX_TURNS:]
            if t.get("content")
        ]
        # Every brand the shopper could be offered. The orchestrator refuses an
        # answer that names a catalogue brand outside the looks on offer.
        catalogue_brands = sorted(
            {
                p.brand.brand_name
                for p in all_products
                if getattr(p, "brand", None) is not None and getattr(p.brand, "brand_name", None)
            }
        )

        # 7. Generate Natural Language Explanation GROUNDED ON THE SELECTED OUTFIT
        ai_result = await self.orchestrator.generate_styling_advice(
            prompt=prompt,
            user_style_tags=user_styles,
            preferred_colors=user_colors,
            budget_limit=max_budget,
            selected_outfit=primary_outfit,
            # Every look shown gets described, in the same call. Sending only
            # outfit[0] meant the second recommendation reached the shopper
            # with a template string that never named what was in it.
            alternate_outfits=recommended_outfits[1:],
            intent=intent,
            extra_context=extra_context,
            conversation=conversation,
            catalogue_brands=catalogue_brands,
        )

        # Split the reply and attach each grounded sentence to its outfit.
        # A sentence that does not name anything really in that outfit is
        # dropped and the template stands: a wrong description is worse than
        # a generic one.
        advice_text = ai_result.get("styling_advice_text", "") or ""
        main_text, outfit_notes = split_outfit_prose(advice_text)
        if outfit_notes:
            attached = attach_prose(recommended_outfits, outfit_notes)
            intent["alternate_prose_attached"] = attached
            if main_text:
                ai_result["styling_advice_text"] = main_text

        # 8. Save assistant response
        #
        # WHICH ENGINE ANSWERED IS PART OF THE RECORD, NOT A LOG DETAIL.
        # The orchestrator already labels the answer truthfully — a real call
        # returns "<Provider> <model the provider actually served>", and a total
        # provider failure returns "CONFIT Grounded Styling Engine". That label
        # used to be computed and then DROPPED here: not persisted, not returned,
        # so neither the consumer nor a reviewer could tell a provider answer
        # from deterministic fallback prose while the capability flag still said
        # the stylist was live. It is now written into the stored message and
        # returned to the caller.
        engine = ai_result.get("provider_used")
        intent["engine"] = engine
        answer_source = ai_result.get("answer_source")
        if answer_source:
            intent["answer_source"] = answer_source

        # 8b. Outbound language: answer in the shopper's language.
        #
        # Measured on production 2026-10-01: an Arabic prompt received an
        # English reply. The inbound layer (translate_query) makes retrieval
        # work; this makes the ANSWER readable for the primary market.
        # Only the stylist's prose is translated — recommendation payloads
        # (prices, titles, scores) stay in their catalogue language, which the
        # Arabic UI already renders. On any translation failure the English
        # prose ships unchanged (honest degradation), and 'reply_language'
        # records what actually happened.
        final_content = ai_result.get("styling_advice_text", "Here is your curated complete look.")
        if contains_arabic(prompt or ""):
            outbound = await translate_reply_to_arabic(final_content)
            if outbound.translated:
                final_content = outbound.text
            intent["reply_language"] = "ar" if outbound.translated else "en"
        else:
            intent["reply_language"] = "en"

        assistant_msg = self.stylist_repo.add_message(
            session_id=session.id,
            sender="assistant",
            content=final_content,
            intent_json=intent,
            recommendations_json=recommended_outfits
        )

        return {
            "id": assistant_msg.id,
            "session_id": session.id,
            "sender": "assistant",
            "content": assistant_msg.content,
            "audio_url": None,
            "intent_detected": intent,
            "engine": engine,
            "answer_source": answer_source,
            "mode": mode_used,
            "fallback_reason": fallback_reason,
            "image_analysis": image_analysis,
            "recommendations": recommended_outfits,
            "created_at": assistant_msg.created_at
        }


#: Earlier turns sent to the model. Matches the request schema bound; a longer
#: history is truncated to the most recent turns, never refused.
STYLIST_HISTORY_MAX_TURNS = 8


# ---------------------------------------------------------------------------
# Request-fact helpers. Pure functions over the shopper's text.
# ---------------------------------------------------------------------------

_LOOK_COUNT_RE = re.compile(
    r"(?<![\w.])(\d{1,2})\s+(?:[a-z]+\s+){0,2}(?:outfits?|looks?|combinations?|sets?)\b", re.IGNORECASE
)
_OWN_ITEM_RE = re.compile(
    r"\b(?:i (?:have|own)|my (?:own|wardrobe|shirt|trousers|pants|jeans|jacket|shoes|vest|blazer|dress)|"
    r"items? i (?:already )?own|what i (?:already )?have)\b|عندي|عندى|ملابسي|ملابسى|عنديّ",
    re.IGNORECASE,
)


def _requested_look_count(prompt: str) -> Optional[int]:
    """The number of looks the shopper asked for, when they state one."""
    match = _LOOK_COUNT_RE.search(prompt or "")
    if not match:
        return None
    count = int(match.group(1))
    return count if 1 <= count <= 20 else None


def _mentions_own_items(prompt: str) -> bool:
    """Whether the shopper talks about clothes they already have."""
    return bool(_OWN_ITEM_RE.search(prompt or ""))


# ---------------------------------------------------------------------------
# Mode A helpers. Pure functions over already-validated data.
# ---------------------------------------------------------------------------

#: Palette shares below this are sampling noise (anti-aliasing, shadows).
_MIN_DOMINANT_SHARE = 0.05

_WARDROBE_CATEGORY_FOR_POSITION = {
    "top": "Tops",
    "dress": "Tops",
    "bottom": "Bottoms",
    "outerwear": "Outerwear",
    "footwear": "Footwear",
    "shoes": "Footwear",
    "accessory": "Accessories",
}


def _cross_check_colours(
    pixel_palettes: List[List[PaletteColor]], vision: VisionAnalysis
) -> "tuple[List[Dict[str, Any]], List[Dict[str, Any]]]":
    """Compare the model's colour words with what the pixels actually show.

    A model colour counts only if the sampled pixels support it. Anything else is
    reported as uncertain and kept out of the palette used for coordination, so a
    hallucinated colour cannot steer the advice.
    """
    merged = merge_palettes(pixel_palettes)
    dominant = [c for c in merged if c.share >= _MIN_DOMINANT_SHARE]
    dominant_families = {c.family for c in dominant}
    checks: List[Dict[str, Any]] = []
    for garment in vision.garments:
        if not garment.color_family:
            continue
        corroborated = garment.color_family in dominant_families
        checks.append({
            "garment": garment.description or garment.category,
            "model_colour": garment.color_family,
            "corroborated_by_pixels": corroborated,
            "status": "confirmed" if corroborated else "uncertain",
        })
    palette_items = [
        {"color_family": c.family, "position": "image", "product_title": "", "hex": c.hex}
        for c in dominant
    ]
    return checks, palette_items


def _coordinate_with_palette(outfit: Dict[str, Any], palette_items: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Score a look against the photo's palette with ColorHarmonyEngine."""
    look_items = [
        {
            "color_family": (it.get("color_family") or it.get("color_name") or "").lower(),
            "position": it.get("position"),
            "product_title": it.get("product_title", ""),
        }
        for it in (outfit.get("items") or [])
    ]
    evaluation = ColorHarmonyEngine.evaluate_palette(look_items + palette_items)
    return {
        "score": evaluation.get("color_harmony_score"),
        "harmony_type": evaluation.get("harmony_type"),
        "verdict": evaluation.get("verdict"),
        "image_colours": [p["color_family"] for p in palette_items],
        "method": "ColorHarmonyEngine over the look plus the pixel-extracted photo palette",
    }


def _hex_family(color_hex: Optional[str]) -> Optional[str]:
    value = (color_hex or "").strip().lstrip("#")
    if len(value) != 6:
        return None
    try:
        rgb = tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return None
    return color_family_for_rgb(rgb)


def _wardrobe_pairings(outfit: Dict[str, Any], owned: List[Any], limit: int = 3) -> List[Dict[str, Any]]:
    """Owned pieces that pair with a look.

    A piece qualifies when its category is NOT already in the look (a second pair
    of trousers is not a pairing) and its colour harmonises with at least one
    piece in the look. Ranked by how many look pieces it harmonises with.
    """
    look = [
        {
            "position": it.get("position"),
            "family": (it.get("color_family") or "").lower(),
        }
        for it in (outfit.get("items") or [])
    ]
    present_categories = {
        _WARDROBE_CATEGORY_FOR_POSITION.get(p["position"]) for p in look if p["position"]
    }
    scored: List[tuple] = []
    for piece in owned:
        category = (piece.category or "").strip().title()
        if category in present_categories:
            continue
        if category not in {"Tops", "Bottoms", "Outerwear", "Footwear", "Accessories"}:
            continue
        family = _hex_family(piece.color_hex) or (piece.color_name or "").lower()
        if not family:
            continue
        pairs_with = []
        for look_piece in look:
            if not look_piece["family"]:
                continue
            if ColorHarmonyEngine._pairs_harmonize(family, look_piece["family"]):
                pairs_with.append(look_piece["position"])
        if not pairs_with:
            continue
        scored.append((len(pairs_with), piece, family, sorted(set(pairs_with))))
    scored.sort(key=lambda row: (-row[0], row[1].id))
    return [
        {
            "wardrobe_item_id": piece.id,
            "title": piece.title,
            "category": category_label(piece.category),
            "color_name": piece.color_name,
            "color_family": family,
            "pairs_with": pairs,
        }
        for _, piece, family, pairs in scored[:limit]
    ]


def category_label(value: Optional[str]) -> str:
    return (value or "").strip().title()
